Skedulo/SkeduloTest/force-app/main/default/objects/LogEvent__e/fields/Current_User__c.field-meta.xml
<CustomField>
    <fullName>Current_User__c</fullName>
    <label>Current User</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Skedulo/SkeduloTest/force-app/main/default/objects/LogEvent__e/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <label>Handler</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Skedulo/SkeduloTest/force-app/main/default/classes/LogEventTriggerTest.cls
@isTest
public with sharing class LogEventTriggerTest {
    
    @isTest
    static void testTrigger(){
        Test.startTest();
        LogEvent__e logEvent = new LogEvent__e ();
        logEvent.Current_User__c = 'Test';
        logEvent.Message__c = 'Test';
        logEvent.Handler__c = 'Test';
        logEvent.Parameters__c = 'Test';
        logEvent.Type__c = 'Error';
        EventBus.publish(logEvent);
        Test.stopTest();
    }
}